#!/bin/bash
source option-lpy.sh
source option-ldk.sh
source option-h.sh

RED='\033[0;31m'
NC='\033[0m' # No Color
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
echo -e "${BLUE}"
echo "
	 ______      __   ___    _____     ____   ______      _____   _____    ________  
(_  __ \    () ) / __)  / ____\   / ___) (   __ \    (_   _) (  __ \  (___  ___) 
  ) ) \ \   ( (_/ /    ( (___    / /      ) (__) )     | |    ) )_) )     ) )    
 ( (   ) )  ()   (      \___ \  ( (      (    __/      | |   (  ___/     ( (     
  ) )  ) )  () /\ \         ) ) ( (       ) \ \  _     | |    ) )         ) )    
 / /__/ /   ( (  \ \    ___/ /   \ \___  ( ( \ \_))   _| |__ ( (         ( (     
(______/    ()_)  \_\  /____/     \____)  )_) \__/   /_____( /__\        /__\    
                                                                                 

"
echo -e "\n \t \t \t ${RED}"
echo -e "   [------------------------------------------------------------]\n"
echo -e "   [                Welcome to DKScript Tool                    ]\n"
echo -e "   [------------------------------------------------------------]\n ${NC}"
echo -e "\n"


while true ; do

if [[ $# -eq 0 ]]; then
echo -e "\n${YELLOW} 1: ${NC} Afficher l'Utilisation des Disques."
echo -e "${YELLOW} 2: ${NC} Afficher les Information Relatives au Disques."
echo -e "${YELLOW} 3: ${NC} Help."
echo -e "${YELLOW} 4: ${NC} Exit."
fi

if [[ $# -eq 0 ]]; then
echo -e "\n ${BLUE}" 
read -p "DK5cr1p7 ➡ " Choix
echo -e "\n ${NC}"
else
Choix=$1
fi

case "$Choix" in

	"-lpy")
		option-lpy
		exit

		;;
	"-ldk")
		option-ldk
		exit
		;;
	"-help" | "-h")
		option-h
		exit
		;;
	"-version" | "-v")
	 		cat version.txt
	 		exit
	 		;;
	"1")
			option-lpy
			while true ; do
			if [[ $# -eq 0 ]]; then
			echo -e "\n ${BLUE}" 
			read -p "DK5cr1p7 - SAVE (y/N) ? ➡ " PID
			echo -e "\n ${NC}"
			else
			save=$1
			fi
			if [[ $save -eq "y" ]]; then
			option-lpy >> output-lpy.txt;
			fi
			break
			done
		;;
	"2")
		option-ldk
		while true ; do
			if [[ $# -eq 0 ]]; then
			echo -e "\n ${BLUE}" 
			read -p "DK5cr1p7 - SAVE (y/N) ? ➡ " PID
			echo -e "\n ${NC}"
			else
			save=$1
			fi
			if [[ $save -eq "y" ]]; then
			option-ldk >> output-ldk.txt;
			fi
			break
			done
		;;
	"3")
		option-h
		;;
	"4"| "exit")
	 echo -e "
		[++] Shutting down ... Goodbye. ( ^_^)／
	   "
		echo -e "\n \t \t   ${YELLOW}Thank you for using HWScript Tool ${RED}<3${NC}"
		exit
		;;
		*)
		option-h
		exit
	  ;;

esac
done
