#!/bin/bash
	sudo apt-get update
	sudo apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget
	cd /tmp
	wget https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
	tar -xf Python-3.7.2.tar.xz
	cd Python-3.7.2
	./configure --enable-optimizations
	sudo make altinstall
	echo "VERIFICATION"	
	python3.7 --version
	sudo apt-get install pydf
